unstable_features             = true
use_small_heuristics          = "Default"
indent_style                  = "Block"
tab_spaces                    = 2
reorder_impl_items            = false
space_before_colon            = false
fn_single_line                = false
where_single_line             = false
struct_lit_single_line        = false
struct_field_align_threshold  = 80
max_width                     = 110
# leave off for now due to glitches
use_field_init_shorthand      = false
